version: '3.9'

name: nestjs

services:
    postgres:
        container_name: postgres
        image: postgres:16-alpine
        restart: always
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=nestjs
        ports:
            - 5432:5432
        networks:
            - nestjs
        volumes:
            - postgres_data:/var/lib/postgresql/data
    minio:
        container_name: minio
        image: docker.io/bitnami/minio:2023
        ports:
            - '9000:9000'
            - '9001:9001'
        volumes:
            - 'minio_data:/bitnami/minio/data'
        environment:
            - MINIO_ROOT_USER=minioadmin
            - MINIO_ROOT_PASSWORD=minioadmin
            - MINIO_SERVER_ACCESS_KEY=minio-access-key
            - MINIO_SERVER_SECRET_KEY=minio-secret-key
        networks:
            - nestjs
    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - 8080:8080
        environment:
            - ADMINER_DEFAULT_SERVER=postgres
        networks:
            - nestjs
    redis:
        container_name: redis
        image: redis:alpine
        restart: always
        ports:
            - 6379:6379
        networks:
            - nestjs
        volumes:
            - redis_data:/data
volumes:
    minio_data:
    postgres_data:
    redis_data:

networks:
    nestjs:
