version: "3.9"
services:
  mysql:
    container_name: mysql
    image: mysql:8
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 3306:3306
    command:
      - --bind-address=0.0.0.0
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
